# Generated by Django 4.2.7 on 2023-12-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='fare_per_passenger',
            new_name='fare',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='route',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='toUniversity',
        ),
        migrations.AddField(
            model_name='trip',
            name='arrival_point',
            field=models.CharField(default='Univalle', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='current_trip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='seats',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='starting_point',
            field=models.CharField(default='Norte', max_length=255),
            preserve_default=False,
        ),
    ]
