# Generated by Django 4.2.7 on 2024-02-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PassangerTrip',
            new_name='Passanger_Trip',
        ),
    ]
