# Generated by Django 4.2.7 on 2024-02-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_passangertrip_passanger_trip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passanger_Trip',
            new_name='Passenger_Trip',
        ),
        migrations.RenameField(
            model_name='passenger_trip',
            old_name='id_passanger_trip',
            new_name='id_passenger_trip',
        ),
    ]
