# Generated by Django 4.2.7 on 2024-03-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_residence_city_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger_trip',
            name='seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
