# Generated by Django 4.2.7 on 2024-04-02 01:31

import api.custom_validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='api.vehicle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passenger_trip',
            name='seats',
            field=models.IntegerField(validators=[api.custom_validators.validate_seats]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fare',
            field=models.IntegerField(validators=[api.custom_validators.validate_fare]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='seats',
            field=models.IntegerField(validators=[api.custom_validators.validate_seats]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[api.custom_validators.validate_lowercase_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity_document',
            field=models.CharField(max_length=10, validators=[api.custom_validators.validate_identity_document]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[api.custom_validators.validate_phone_number]),
        ),
    ]
