# Generated by Django 4.2.7 on 2024-04-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_trip_vehicle_alter_passenger_trip_seats_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='passenger_trip',
            constraint=models.UniqueConstraint(fields=('passenger', 'trip'), name='Passenger_Trip_Unique'),
        ),
    ]
