# Generated by Django 4.2.7 on 2024-04-21 06:53

import api.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_passenger_trip_passenger_trip_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger_trip',
            name='pickup_point',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='arrival_point',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='starting_point',
        ),
        migrations.AddField(
            model_name='passenger_trip',
            name='pickup_point_lat',
            field=models.DecimalField(decimal_places=6, default=3.375462, max_digits=8, validators=[api.custom_validators.validate_latitude]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger_trip',
            name='pickup_point_long',
            field=models.DecimalField(decimal_places=6, default=-76.533166, max_digits=9, validators=[api.custom_validators.validate_longitude]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='arrival_point_lat',
            field=models.DecimalField(decimal_places=6, default=3.375462, max_digits=8, validators=[api.custom_validators.validate_latitude]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='arrival_point_long',
            field=models.DecimalField(decimal_places=6, default=-76.533166, max_digits=9, validators=[api.custom_validators.validate_longitude]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='starting_point_lat',
            field=models.DecimalField(decimal_places=6, default=3.375462, max_digits=8, validators=[api.custom_validators.validate_latitude]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='starting_point_long',
            field=models.DecimalField(decimal_places=6, default=-76.533166, max_digits=9, validators=[api.custom_validators.validate_longitude]),
            preserve_default=False,
        ),
    ]
