# Generated by Django 4.2.7 on 2024-05-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_device_id_device'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='passenger_trip',
            name='Passenger_Trip_Unique',
        ),
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='License_plate_Owner_Unique',
        ),
        migrations.AddConstraint(
            model_name='passenger_trip',
            constraint=models.UniqueConstraint(fields=('passenger', 'trip'), name='passenger_trip_unique'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('start_date', 'start_time', 'driver'), name='start_datetime_driver_unique'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('license_plate', 'owner'), name='license_plate_owner_unique'),
        ),
    ]
